---
deployment:
  tasks:
    # 1. Tentukan path utama
    - export DEPLOYPATH=/home/rwsmarh/
    
    # 2. Salin SEMUA file (kecuali 'public') dari repo ke 'laravel-app'
    - /bin/rsync -av --exclude 'public/' $DEPLOYPATH/repositories/SmartHub/ $DEPLOYPATH/laravel-app/
    
    # 3. Salin HANYA ISI folder 'public' dari repo ke 'public_html'
    - /bin/rsync -av $DEPLOYPATH/repositories/SmartHub/public/ $DEPLOYPATH/public_html/
    
    # 4. (WAJIB) Perbarui symlink storage
    - /bin/rm -f $DEPLOYPATH/public_html/storage
    - /bin/ln -s $DEPLOYPATH/laravel-app/storage/app/public $DEPLOYPATH/public_html/storage